/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package xyz.brassgoggledcoders.minescribe;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        MineScribeApplication classUnderTest = new MineScribeApplication();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
